num_1=int(input('enter your first number:'))
num_2=int(input('enter your second number:'))
print('{}+{}='.format(num_1,num_2))
print(num_1+num_2)
print('{}-{}='.format(num_1,num_2))
print(num_1-num_2)
print('{}*{}='.format(num_1,num_2))
print(num_1*num_2)
print('{}/{}='.format(num_1,num_2))
print(num_1%num_2)
